services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:  
      - ./frontend/src:/var/www/html

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy  # ヘルスチェックが成功したら起動
    environment:
      DATABASE_URL: "mysql+pymysql://nttdata:intellilink@db/team2_db"

  nginx: 
    build:
      context: ./nginx
    ports:
      - 80:80
    depends_on:
      - backend

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: team2_db
      MYSQL_USER: nttdata
      MYSQL_PASSWORD: intellilink
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
